// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Chat.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Protocol {
  public static partial class EchoChat
  {
    static readonly string __ServiceName = "protocol.EchoChat";

    static readonly grpc::Marshaller<global::Protocol.ChatReq> __Marshaller_protocol_ChatReq = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Protocol.ChatReq.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Protocol.ChatAck> __Marshaller_protocol_ChatAck = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Protocol.ChatAck.Parser.ParseFrom);

    static readonly grpc::Method<global::Protocol.ChatReq, global::Protocol.ChatAck> __Method_SendChat = new grpc::Method<global::Protocol.ChatReq, global::Protocol.ChatAck>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SendChat",
        __Marshaller_protocol_ChatReq,
        __Marshaller_protocol_ChatAck);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Protocol.ChatReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of EchoChat</summary>
    [grpc::BindServiceMethod(typeof(EchoChat), "BindService")]
    public abstract partial class EchoChatBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Protocol.ChatAck> SendChat(global::Protocol.ChatReq request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for EchoChat</summary>
    public partial class EchoChatClient : grpc::ClientBase<EchoChatClient>
    {
      /// <summary>Creates a new client for EchoChat</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public EchoChatClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for EchoChat that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public EchoChatClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected EchoChatClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected EchoChatClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Protocol.ChatAck SendChat(global::Protocol.ChatReq request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SendChat(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Protocol.ChatAck SendChat(global::Protocol.ChatReq request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SendChat, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Protocol.ChatAck> SendChatAsync(global::Protocol.ChatReq request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SendChatAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Protocol.ChatAck> SendChatAsync(global::Protocol.ChatReq request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SendChat, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override EchoChatClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new EchoChatClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(EchoChatBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_SendChat, serviceImpl.SendChat).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, EchoChatBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_SendChat, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Protocol.ChatReq, global::Protocol.ChatAck>(serviceImpl.SendChat));
    }

  }
}
#endregion
