// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: HeartBeat.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Protocol {
  public static partial class EchoHeartBeat
  {
    static readonly string __ServiceName = "protocol.EchoHeartBeat";

    static readonly grpc::Marshaller<global::Protocol.HeartBeatReq> __Marshaller_protocol_HeartBeatReq = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Protocol.HeartBeatReq.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Protocol.HeartBeatAck> __Marshaller_protocol_HeartBeatAck = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Protocol.HeartBeatAck.Parser.ParseFrom);

    static readonly grpc::Method<global::Protocol.HeartBeatReq, global::Protocol.HeartBeatAck> __Method_HeartBeat = new grpc::Method<global::Protocol.HeartBeatReq, global::Protocol.HeartBeatAck>(
        grpc::MethodType.Unary,
        __ServiceName,
        "HeartBeat",
        __Marshaller_protocol_HeartBeatReq,
        __Marshaller_protocol_HeartBeatAck);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Protocol.HeartBeatReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of EchoHeartBeat</summary>
    [grpc::BindServiceMethod(typeof(EchoHeartBeat), "BindService")]
    public abstract partial class EchoHeartBeatBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Protocol.HeartBeatAck> HeartBeat(global::Protocol.HeartBeatReq request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for EchoHeartBeat</summary>
    public partial class EchoHeartBeatClient : grpc::ClientBase<EchoHeartBeatClient>
    {
      /// <summary>Creates a new client for EchoHeartBeat</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public EchoHeartBeatClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for EchoHeartBeat that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public EchoHeartBeatClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected EchoHeartBeatClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected EchoHeartBeatClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Protocol.HeartBeatAck HeartBeat(global::Protocol.HeartBeatReq request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return HeartBeat(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Protocol.HeartBeatAck HeartBeat(global::Protocol.HeartBeatReq request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_HeartBeat, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Protocol.HeartBeatAck> HeartBeatAsync(global::Protocol.HeartBeatReq request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return HeartBeatAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Protocol.HeartBeatAck> HeartBeatAsync(global::Protocol.HeartBeatReq request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_HeartBeat, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override EchoHeartBeatClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new EchoHeartBeatClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(EchoHeartBeatBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_HeartBeat, serviceImpl.HeartBeat).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, EchoHeartBeatBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_HeartBeat, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Protocol.HeartBeatReq, global::Protocol.HeartBeatAck>(serviceImpl.HeartBeat));
    }

  }
}
#endregion
